DATA_ROOT: "/home/oahmed6/scr16_blangme2/oahmed/spumoni_exps/exp_2a"
NUM_DATASETS: 4
REPO_DIR: "/home/oahmed6/spumoni_exps"
SPUMONI_DIR: "/home/oahmed6/spumoni/build"
PBSIM_MODEL: "/home/oahmed6/pbsim2/data/R95.model"
READS_PER_DATASET: 2000