DATA_ROOT: "/home/oahmed6/scr16_blangme2/oahmed/spumoni_exps/exp_5"
NUM_DATASETS: 1
REPO_DIR: "/home/oahmed6/spumoni_exps"
SPUMONI_DIR: "/home/oahmed6/spumoni/build"
PBSIM_MODEL: "/home/oahmed6/pbsim2/data/R94.model"
READS_PER_DATASET: 2000
DATASET_NAME_EXP2: "ecoli_500"
NUM_READS_EXP3: 10000
ILLUMINA_MISMATCH_PROB_EXP3: 0.01
LONG_READ_ACC_EXP3: 0.95
NUM_READS_EXP4: 10000
ILLUMINA_MISMATCH_PROB_EXP4: 0.01
LONG_READ_ACC_EXP4: 0.95
