DATA_ROOT: "/home/oahmed/storage/storage1/spumoni_exps/exp_3"
NUM_DATASETS: 1
REPO_DIR: "/home/oahmed6/spumoni_exps"
SPUMONI_DIR: "/home/oahmed6/spumoni/build"
PBSIM_MODEL: "/home/oahmed/code/pbsim2/data/R94.model"
READS_PER_DATASET: 2000
DATASET_NAME: "ecoli_10"
NUM_READS_EXP3: 5000
