DATA_ROOT: "/home/oahmed6/scr16_blangme2/oahmed/spumoni_exps/exp_7"
NUM_DATASETS: 2
REPO_DIR: "/home/oahmed6/spumoni_exps"
SPUMONI_DIR: "/home/oahmed6/spumoni/build"
PBSIM_MODEL: "/home/oahmed6/pbsim2/data/R94.model"
TIME_PROG: "/usr/bin/time"
TIME_FORMAT: "--format='user= %U system= %S elapsed= %e CPU= %P MemMax= %M'"
READS_PER_DATASET: 2000
DATASET_NAME_EXP2: "ecoli_500"
NUM_READS_EXP3: 10000
ILLUMINA_MISMATCH_PROB_EXP3: 0.01
LONG_READ_ACC_EXP3: 0.95
NUM_READS_EXP4: 10000
ILLUMINA_MISMATCH_PROB_EXP4: 0.01
LONG_READ_ACC_EXP4: 0.95
NUM_READS_EXP6: 1000000
ILLUMINA_MISMATCH_PROB_EXP6: 0.01
NUM_POS_READS_EXP7: 500000
NUM_NULL_READS_EXP7: 500000
LONG_READ_ACC_EXP7: 0.95
